// Code generated by gen/remote.js from controllers.go and sim.go; DO NOT EDIT.

package world

import (
	"time"

	"github.com/mrlm-net/simconnect/pkg/airport"
	"github.com/mrlm-net/simconnect/pkg/engine"
	"github.com/mrlm-net/simconnect/pkg/traffic"
	"github.com/mrlm-net/simconnect/pkg/types"
)

var (
	_ = time.Second
	_ airport.LatLon
	_ types.SIMCONNECT_DATA_WAYPOINT
	_ traffic.RoutePoint
)

// remoteDep is the director's departureCtl: each call a wire call.
func (r *remoteDep) SetPushbackAt(at time.Time) bool {
	var o0 bool
	r.c.dropped(r.c.call(r.t, "SetPushbackAt", []any{at}, &o0))
	return o0
}

func (r *remoteDep) ClearPushback() {
	r.c.dropped(r.c.call(r.t, "ClearPushback", []any{}))
}

func (r *remoteDep) FacesOut() bool {
	var o0 bool
	r.c.dropped(r.c.call(r.t, "FacesOut", []any{}, &o0))
	return o0
}

func (r *remoteDep) ClearToTaxi() {
	r.c.dropped(r.c.call(r.t, "ClearToTaxi", []any{}))
}

func (r *remoteDep) ClearUpTo(node airport.NodeID) error {
	err := r.c.call(r.t, "ClearUpTo", []any{node})
	return err
}

func (r *remoteDep) Cancel() error {
	err := r.c.call(r.t, "Cancel", []any{})
	return err
}

func (r *remoteDep) HoldPosition() error {
	err := r.c.call(r.t, "HoldPosition", []any{})
	return err
}

func (r *remoteDep) AbortTakeoff() error {
	err := r.c.call(r.t, "AbortTakeoff", []any{})
	return err
}

func (r *remoteDep) ChangeEntry(entry string) error {
	err := r.c.call(r.t, "ChangeEntry", []any{entry})
	return err
}

func (r *remoteDep) TaxiVia(via []airport.NodeID) error {
	err := r.c.call(r.t, "TaxiVia", []any{via})
	return err
}

func (r *remoteDep) ChangeRunway(runway string, entry string, departure []airport.NavPoint) error {
	err := r.c.call(r.t, "ChangeRunway", []any{runway, entry, departure})
	return err
}

func (r *remoteDep) ClearForTakeoff() error {
	err := r.c.call(r.t, "ClearForTakeoff", []any{})
	return err
}

func (r *remoteDep) ClearPushbackFacing(dir string) error {
	err := r.c.call(r.t, "ClearPushbackFacing", []any{dir})
	return err
}

func (r *remoteDep) ClearStartUp() {
	r.c.dropped(r.c.call(r.t, "ClearStartUp", []any{}))
}

func (r *remoteDep) ClearToCross() {
	r.c.dropped(r.c.call(r.t, "ClearToCross", []any{}))
}

func (r *remoteDep) ClearToLineUp() {
	r.c.dropped(r.c.call(r.t, "ClearToLineUp", []any{}))
}

func (r *remoteDep) ClimbPlan(pos airport.LatLon) []traffic.RoutePoint {
	var o0 []traffic.RoutePoint
	r.c.dropped(r.c.call(r.t, "ClimbPlan", []any{pos}, &o0))
	return o0
}

func (r *remoteDep) ClimbRoute(pos airport.LatLon) []airport.LatLon {
	var o0 []airport.LatLon
	r.c.dropped(r.c.call(r.t, "ClimbRoute", []any{pos}, &o0))
	return o0
}

func (r *remoteDep) DirectTo(pos airport.LatLon, altFt float64, kts float64, fix airport.LatLon) error {
	err := r.c.call(r.t, "DirectTo", []any{pos, altFt, kts, fix})
	return err
}

func (r *remoteDep) Expedite(on bool) {
	r.c.dropped(r.c.call(r.t, "Expedite", []any{on}))
}

func (r *remoteDep) Handle(msg engine.Message) bool { return false } // the actuator handles its messages

func (r *remoteDep) HoldPushback(on bool) {
	r.c.dropped(r.c.call(r.t, "HoldPushback", []any{on}))
}

func (r *remoteDep) PushFacingSaid() string {
	var o0 string
	r.c.dropped(r.c.call(r.t, "PushFacingSaid", []any{}, &o0))
	return o0
}

func (r *remoteDep) Reroute(route []traffic.RoutePoint) error {
	err := r.c.call(r.t, "Reroute", []any{route})
	return err
}

func (r *remoteDep) Route() *airport.Route {
	var o0 *airport.Route
	r.c.dropped(r.c.call(r.t, "Route", []any{}, &o0))
	return o0
}

func (r *remoteDep) State() traffic.TaxiState {
	var o0 traffic.TaxiState
	r.c.dropped(r.c.call(r.t, "State", []any{}, &o0))
	return o0
}

// remoteArr is the director's arrivalCtl: each call a wire call.
func (r *remoteArr) AbsorbDelay(delay time.Duration) (traffic.Absorption, error) {
	var o0 traffic.Absorption
	err := r.c.call(r.t, "AbsorbDelay", []any{delay}, &o0)
	return o0, err
}

func (r *remoteArr) AnotherCircuit() (time.Duration, error) {
	var o0 time.Duration
	err := r.c.call(r.t, "AnotherCircuit", []any{}, &o0)
	return o0, err
}

func (r *remoteArr) Cancel() error {
	err := r.c.call(r.t, "Cancel", []any{})
	return err
}

func (r *remoteArr) ChangeRunway(runway string, procedure []airport.NavPoint, missed []airport.NavPoint) error {
	err := r.c.call(r.t, "ChangeRunway", []any{runway, procedure, missed})
	return err
}

func (r *remoteArr) ChangeStand(parking int) error {
	err := r.c.call(r.t, "ChangeStand", []any{parking})
	return err
}

func (r *remoteArr) CircuitFixes() []airport.NavPoint {
	var o0 []airport.NavPoint
	r.c.dropped(r.c.call(r.t, "CircuitFixes", []any{}, &o0))
	return o0
}

func (r *remoteArr) ClearToCross() {
	r.c.dropped(r.c.call(r.t, "ClearToCross", []any{}))
}

func (r *remoteArr) ClearToTaxi() {
	r.c.dropped(r.c.call(r.t, "ClearToTaxi", []any{}))
}

func (r *remoteArr) ClearUpTo(node airport.NodeID) error {
	err := r.c.call(r.t, "ClearUpTo", []any{node})
	return err
}

func (r *remoteArr) DirectToJoin() error {
	err := r.c.call(r.t, "DirectToJoin", []any{})
	return err
}

func (r *remoteArr) DirectTo(p airport.LatLon) (string, traffic.Vector, error) {
	var o0 string
	var o1 traffic.Vector
	err := r.c.call(r.t, "DirectTo", []any{p}, &o0, &o1)
	return o0, o1, err
}

func (r *remoteArr) JoinFinal(p airport.LatLon) (float64, traffic.Vector, error) {
	var o0 float64
	var o1 traffic.Vector
	err := r.c.call(r.t, "JoinFinal", []any{p}, &o0, &o1)
	return o0, o1, err
}

func (r *remoteArr) AssignSpeed(kts float64) (float64, error) {
	var o0 float64
	err := r.c.call(r.t, "AssignSpeed", []any{kts}, &o0)
	return o0, err
}

func (r *remoteArr) EnterHold(h traffic.Hold, altFt float64) (traffic.HoldEntry, error) {
	var o0 traffic.HoldEntry
	err := r.c.call(r.t, "EnterHold", []any{h, altFt}, &o0)
	return o0, err
}

func (r *remoteArr) Expedite(on bool) {
	r.c.dropped(r.c.call(r.t, "Expedite", []any{on}))
}

func (r *remoteArr) GoAround() error {
	err := r.c.call(r.t, "GoAround", []any{})
	return err
}

func (r *remoteArr) Handle(msg engine.Message) bool { return false } // the actuator handles its messages

func (r *remoteArr) HoldAltitude(altFt float64) error {
	err := r.c.call(r.t, "HoldAltitude", []any{altFt})
	return err
}

func (r *remoteArr) HoldFix(minFromThresholdNM float64) (traffic.Hold, bool) {
	var o0 traffic.Hold
	var o1 bool
	r.c.dropped(r.c.call(r.t, "HoldFix", []any{minFromThresholdNM}, &o0, &o1))
	return o0, o1
}

func (r *remoteArr) Holding() (traffic.Hold, float64, bool) {
	var o0 traffic.Hold
	var o1 float64
	var o2 bool
	r.c.dropped(r.c.call(r.t, "Holding", []any{}, &o0, &o1, &o2))
	return o0, o1, o2
}

func (r *remoteArr) HoldPosition() error {
	err := r.c.call(r.t, "HoldPosition", []any{})
	return err
}

func (r *remoteArr) InterceptHeading() (float64, bool) {
	var o0 float64
	var o1 bool
	r.c.dropped(r.c.call(r.t, "InterceptHeading", []any{}, &o0, &o1))
	return o0, o1
}

func (r *remoteArr) LeaveHold() error {
	err := r.c.call(r.t, "LeaveHold", []any{})
	return err
}

func (r *remoteArr) Orbit() (time.Duration, error) {
	var o0 time.Duration
	err := r.c.call(r.t, "Orbit", []any{}, &o0)
	return o0, err
}

func (r *remoteArr) Plan() *traffic.ArrivalPlan {
	var o0 *traffic.ArrivalPlan
	r.c.dropped(r.c.call(r.t, "Plan", []any{}, &o0))
	return o0
}

func (r *remoteArr) ProcedurePlan() []traffic.RoutePoint {
	var o0 []traffic.RoutePoint
	r.c.dropped(r.c.call(r.t, "ProcedurePlan", []any{}, &o0))
	return o0
}

func (r *remoteArr) ProcedureRoute() []airport.LatLon {
	var o0 []airport.LatLon
	r.c.dropped(r.c.call(r.t, "ProcedureRoute", []any{}, &o0))
	return o0
}

func (r *remoteArr) ProcedureCorners() []airport.LatLon {
	var o0 []airport.LatLon
	r.c.dropped(r.c.call(r.t, "ProcedureCorners", []any{}, &o0))
	return o0
}

func (r *remoteArr) ReduceToFinalSpeed() (time.Duration, error) {
	var o0 time.Duration
	err := r.c.call(r.t, "ReduceToFinalSpeed", []any{}, &o0)
	return o0, err
}

func (r *remoteArr) Shortcut(maxSaveNM float64, keep []string) (string, float64, error) {
	var o0 string
	var o1 float64
	err := r.c.call(r.t, "Shortcut", []any{maxSaveNM, keep}, &o0, &o1)
	return o0, o1, err
}

func (r *remoteArr) State() traffic.ArrivalState {
	var o0 traffic.ArrivalState
	r.c.dropped(r.c.call(r.t, "State", []any{}, &o0))
	return o0
}

func (r *remoteArr) StopDescent(altFt float64, forNM float64) error {
	err := r.c.call(r.t, "StopDescent", []any{altFt, forNM})
	return err
}

func (r *remoteArr) TouchAndGosLeft() int {
	var o0 int
	r.c.dropped(r.c.call(r.t, "TouchAndGosLeft", []any{}, &o0))
	return o0
}

func (r *remoteArr) TurningFinal() bool {
	var o0 bool
	r.c.dropped(r.c.call(r.t, "TurningFinal", []any{}, &o0))
	return o0
}

func (r *remoteArr) VectorDue() (traffic.Vector, bool) {
	var o0 traffic.Vector
	var o1 bool
	r.c.dropped(r.c.call(r.t, "VectorDue", []any{}, &o0, &o1))
	return o0, o1
}

// remoteSim is the director's simPort: each call a wire call.
func (r *remoteSim) SpawnEnroute(o traffic.NonATCOpts, reqID uint32) error {
	err := r.c.call(r.t, "SpawnEnroute", []any{o, reqID})
	return err
}

func (r *remoteSim) FlyEnroute(reqID uint32, objectID uint32, wps []types.SIMCONNECT_DATA_WAYPOINT) error {
	err := r.c.call(r.t, "FlyEnroute", []any{reqID, objectID, wps})
	return err
}

func (r *remoteSim) SetRoute(objectID uint32, wps []types.SIMCONNECT_DATA_WAYPOINT) error {
	err := r.c.call(r.t, "SetRoute", []any{objectID, wps})
	return err
}

func (r *remoteSim) RemoveObject(objectID uint32, reqID uint32) error {
	err := r.c.call(r.t, "RemoveObject", []any{objectID, reqID})
	return err
}

func (r *remoteSim) ListModels() error {
	err := r.c.call(r.t, "ListModels", []any{})
	return err
}

func (r *remoteSim) ListGroundVehicles() error {
	err := r.c.call(r.t, "ListGroundVehicles", []any{})
	return err
}

