package registry

// simvars is the authoritative list of MSFS SimVar metadata entries.
// Sourced from: pkg/datasets/aircraft, environment, simulator, objects, traffic,
// and pkg/manager/simstate_registration.go.
//
// Rules:
//   - Each base SimVar name appears exactly once (deduplicated across packages).
//   - Indexed vars use the base name without :N suffix; Indexed: true.
//   - Unit strings are lowercase canonical form.
//   - String-typed vars use Units: []string{"string"}, Type: "string".
var simvars = []SimVarMeta{
	// -------------------------------------------------------------------------
	// Aircraft — position & orientation
	// -------------------------------------------------------------------------
	{
		Name:        "PLANE LATITUDE",
		Units:       []string{"degrees", "radians"},
		DefaultUnit: "degrees",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    true,
		Indexed:     false,
		Description: "Latitude of the aircraft in degrees north of the equator.",
	},
	{
		Name:        "PLANE LONGITUDE",
		Units:       []string{"degrees", "radians"},
		DefaultUnit: "degrees",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    true,
		Indexed:     false,
		Description: "Longitude of the aircraft in degrees east of the prime meridian.",
	},
	{
		Name:        "PLANE ALTITUDE",
		Units:       []string{"feet", "meters"},
		DefaultUnit: "feet",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    true,
		Indexed:     false,
		Description: "Altitude of the aircraft above mean sea level.",
	},
	{
		Name:        "PLANE PITCH DEGREES",
		Units:       []string{"degrees", "radians"},
		DefaultUnit: "degrees",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    false,
		Indexed:     false,
		Description: "Pitch angle of the aircraft (positive = nose up).",
	},
	{
		Name:        "PLANE BANK DEGREES",
		Units:       []string{"degrees", "radians"},
		DefaultUnit: "degrees",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    false,
		Indexed:     false,
		Description: "Bank angle of the aircraft (positive = right wing down).",
	},
	{
		Name:        "PLANE HEADING DEGREES TRUE",
		Units:       []string{"degrees", "radians"},
		DefaultUnit: "degrees",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    true,
		Indexed:     false,
		Description: "True heading of the aircraft in degrees.",
	},
	{
		Name:        "PLANE HEADING DEGREES MAGNETIC",
		Units:       []string{"degrees", "radians"},
		DefaultUnit: "degrees",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    false,
		Indexed:     false,
		Description: "Magnetic heading of the aircraft in degrees.",
	},
	{
		Name:        "VERTICAL SPEED",
		Units:       []string{"feet per minute", "meters per second"},
		DefaultUnit: "feet per minute",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    true,
		Indexed:     false,
		Description: "Vertical speed of the aircraft (positive = climbing).",
	},
	{
		Name:        "GROUND VELOCITY",
		Units:       []string{"knots", "meters per second", "kilometers per hour"},
		DefaultUnit: "knots",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    false,
		Indexed:     false,
		Description: "Speed of the aircraft relative to the ground.",
	},
	{
		Name:        "INDICATED ALTITUDE",
		Units:       []string{"feet", "meters"},
		DefaultUnit: "feet",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    false,
		Indexed:     false,
		Description: "Altitude indicated by the altimeter instrument.",
	},
	{
		Name:        "PLANE ALT ABOVE GROUND",
		Units:       []string{"feet", "meters"},
		DefaultUnit: "feet",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    false,
		Indexed:     false,
		Description: "Altitude of the aircraft above ground level.",
	},

	// -------------------------------------------------------------------------
	// Aircraft — airspeed
	// -------------------------------------------------------------------------
	{
		Name:        "AIRSPEED INDICATED",
		Units:       []string{"knots", "meters per second"},
		DefaultUnit: "knots",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    false,
		Indexed:     false,
		Description: "Indicated airspeed (IAS) as shown on the airspeed indicator.",
	},
	{
		Name:        "AIRSPEED TRUE",
		Units:       []string{"knots", "meters per second"},
		DefaultUnit: "knots",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    false,
		Indexed:     false,
		Description: "True airspeed (TAS) of the aircraft.",
	},
	{
		Name:        "AIRSPEED MACH",
		Units:       []string{"mach"},
		DefaultUnit: "mach",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    false,
		Indexed:     false,
		Description: "Airspeed expressed as a Mach number.",
	},

	// -------------------------------------------------------------------------
	// Aircraft — dimensions
	// -------------------------------------------------------------------------
	{
		Name:        "WING SPAN",
		Units:       []string{"feet", "meters"},
		DefaultUnit: "feet",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    false,
		Indexed:     false,
		Description: "Wingspan of the aircraft.",
	},

	// -------------------------------------------------------------------------
	// Aircraft — engine & fuel
	// -------------------------------------------------------------------------
	{
		Name:        "ENG RPM",
		Units:       []string{"rpm"},
		DefaultUnit: "rpm",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    false,
		Indexed:     true,
		Description: "Engine RPM for the indexed engine (e.g., ENG RPM:1).",
	},
	{
		Name:        "ENG FUEL FLOW GPH",
		Units:       []string{"gallons per hour"},
		DefaultUnit: "gallons per hour",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    false,
		Indexed:     true,
		Description: "Fuel flow in gallons per hour for the indexed engine.",
	},
	{
		Name:        "THROTTLE LOWER LIMIT",
		Units:       []string{"percent"},
		DefaultUnit: "percent",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    false,
		Indexed:     false,
		Description: "Lower limit of the throttle range (negative for reverse thrust capable aircraft).",
	},
	{
		Name:        "FUEL TOTAL QUANTITY",
		Units:       []string{"gallons", "liters"},
		DefaultUnit: "gallons",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    false,
		Indexed:     false,
		Description: "Total quantity of fuel currently loaded across all tanks.",
	},
	{
		Name:        "NUMBER OF ENGINES",
		Units:       []string{"number"},
		DefaultUnit: "number",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    false,
		Indexed:     false,
		Description: "Number of engines installed on the aircraft.",
	},
	{
		Name:        "ENGINE TYPE",
		Units:       []string{"enum"},
		DefaultUnit: "enum",
		Type:        "enum",
		Category:    "aircraft",
		Writable:    false,
		Indexed:     false,
		Description: "Type of engine (0=Piston, 1=Jet, 2=None, 3=Helo turbine, 4=Unsupported, 5=Turboprop).",
	},
	{
		Name:        "GENERAL ENG THROTTLE LEVER POSITION",
		Units:       []string{"percent"},
		DefaultUnit: "percent",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    true,
		Indexed:     true,
		Description: "Throttle lever position as a percentage for the indexed engine.",
	},
	{
		Name:        "FUEL SELECTED QUANTITY",
		Units:       []string{"gallons", "liters"},
		DefaultUnit: "gallons",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    false,
		Indexed:     true,
		Description: "Quantity of fuel in the selected tank for the indexed engine.",
	},

	// -------------------------------------------------------------------------
	// Aircraft — control surfaces & landing
	// -------------------------------------------------------------------------
	{
		Name:        "AILERON POSITION",
		Units:       []string{"position"},
		DefaultUnit: "position",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    true,
		Indexed:     false,
		Description: "Aileron deflection position (-1.0 to 1.0).",
	},
	{
		Name:        "ELEVATOR POSITION",
		Units:       []string{"position"},
		DefaultUnit: "position",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    true,
		Indexed:     false,
		Description: "Elevator deflection position (-1.0 to 1.0).",
	},
	{
		Name:        "RUDDER POSITION",
		Units:       []string{"position"},
		DefaultUnit: "position",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    true,
		Indexed:     false,
		Description: "Rudder deflection position (-1.0 to 1.0).",
	},
	{
		Name:        "FLAPS HANDLE INDEX",
		Units:       []string{"number"},
		DefaultUnit: "number",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    false,
		Indexed:     false,
		Description: "Current flaps handle position index.",
	},
	{
		Name:        "GEAR HANDLE POSITION",
		Units:       []string{"bool"},
		DefaultUnit: "bool",
		Type:        "bool",
		Category:    "aircraft",
		Writable:    true,
		Indexed:     false,
		Description: "Gear handle position (true = down/extended).",
	},
	{
		Name:        "SPOILERS HANDLE POSITION",
		Units:       []string{"percent"},
		DefaultUnit: "percent",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    true,
		Indexed:     false,
		Description: "Spoilers/speedbrakes handle position as a percentage.",
	},
	{
		Name:        "BRAKE PARKING POSITION",
		Units:       []string{"bool"},
		DefaultUnit: "bool",
		Type:        "bool",
		Category:    "aircraft",
		Writable:    true,
		Indexed:     false,
		Description: "Parking brake position (true = set).",
	},

	// -------------------------------------------------------------------------
	// Aircraft — autopilot & avionics
	// -------------------------------------------------------------------------
	{
		Name:        "AUTOPILOT MASTER",
		Units:       []string{"bool"},
		DefaultUnit: "bool",
		Type:        "bool",
		Category:    "aircraft",
		Writable:    true,
		Indexed:     false,
		Description: "Autopilot master switch state (true = engaged).",
	},
	{
		Name:        "AUTOPILOT ALTITUDE LOCK VAR",
		Units:       []string{"feet", "meters"},
		DefaultUnit: "feet",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    true,
		Indexed:     false,
		Description: "Target altitude locked by the autopilot altitude hold mode.",
	},
	{
		Name:        "AUTOPILOT HEADING LOCK DIR",
		Units:       []string{"degrees", "radians"},
		DefaultUnit: "degrees",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    true,
		Indexed:     false,
		Description: "Target heading locked by the autopilot heading hold mode.",
	},
	{
		Name:        "TRANSPONDER CODE",
		Units:       []string{"number"},
		DefaultUnit: "number",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    true,
		Indexed:     false,
		Description: "Transponder squawk code (decimal encoding of the octal code).",
	},
	{
		Name:        "COM ACTIVE FREQUENCY",
		Units:       []string{"mhz"},
		DefaultUnit: "mhz",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    false,
		Indexed:     true,
		Description: "Active COM radio frequency in MHz for the indexed radio.",
	},
	{
		Name:        "NAV OBS",
		Units:       []string{"degrees", "radians"},
		DefaultUnit: "degrees",
		Type:        "float64",
		Category:    "aircraft",
		Writable:    false,
		Indexed:     true,
		Description: "NAV OBS (course) setting in degrees for the indexed NAV radio.",
	},

	// -------------------------------------------------------------------------
	// Aircraft — lighting
	// -------------------------------------------------------------------------
	{
		Name:        "LIGHT STROBE",
		Units:       []string{"bool"},
		DefaultUnit: "bool",
		Type:        "bool",
		Category:    "aircraft",
		Writable:    true,
		Indexed:     false,
		Description: "Strobe light state (true = on).",
	},
	{
		Name:        "LIGHT BEACON",
		Units:       []string{"bool"},
		DefaultUnit: "bool",
		Type:        "bool",
		Category:    "aircraft",
		Writable:    true,
		Indexed:     false,
		Description: "Beacon light state (true = on).",
	},

	// -------------------------------------------------------------------------
	// Aircraft — traffic / identification (string vars)
	// -------------------------------------------------------------------------
	{
		Name:        "TITLE",
		Units:       []string{"string"},
		DefaultUnit: "string",
		Type:        "string",
		Category:    "aircraft",
		Writable:    false,
		Indexed:     false,
		Description: "Full title of the aircraft as defined in its aircraft.cfg.",
	},
	{
		Name:        "CATEGORY",
		Units:       []string{"string"},
		DefaultUnit: "string",
		Type:        "string",
		Category:    "aircraft",
		Writable:    false,
		Indexed:     false,
		Description: "Category of the aircraft (e.g., Airplane, Helicopter).",
	},
	{
		Name:        "LIVERY NAME",
		Units:       []string{"string"},
		DefaultUnit: "string",
		Type:        "string",
		Category:    "aircraft",
		Writable:    false,
		Indexed:     false,
		Description: "Name of the currently applied livery.",
	},
	{
		Name:        "LIVERY FOLDER",
		Units:       []string{"string"},
		DefaultUnit: "string",
		Type:        "string",
		Category:    "aircraft",
		Writable:    false,
		Indexed:     false,
		Description: "Folder name of the currently applied livery.",
	},
	{
		Name:        "ATC ID",
		Units:       []string{"string"},
		DefaultUnit: "string",
		Type:        "string",
		Category:    "aircraft",
		Writable:    false,
		Indexed:     false,
		Description: "ATC identification code for the aircraft (tail number).",
	},
	{
		Name:        "ATC AIRLINE",
		Units:       []string{"string"},
		DefaultUnit: "string",
		Type:        "string",
		Category:    "aircraft",
		Writable:    false,
		Indexed:     false,
		Description: "Airline name used by ATC for this aircraft.",
	},

	// -------------------------------------------------------------------------
	// Aircraft — traffic / ground state (boolean)
	// -------------------------------------------------------------------------
	{
		Name:        "TOW CONNECTION",
		Units:       []string{"bool"},
		DefaultUnit: "bool",
		Type:        "bool",
		Category:    "aircraft",
		Writable:    false,
		Indexed:     false,
		Description: "Whether the aircraft currently has a tow connection.",
	},
	{
		Name:        "ON ANY RUNWAY",
		Units:       []string{"bool"},
		DefaultUnit: "bool",
		Type:        "bool",
		Category:    "aircraft",
		Writable:    false,
		Indexed:     false,
		Description: "Whether the aircraft is on any runway surface.",
	},

	// -------------------------------------------------------------------------
	// Environment — weather
	// -------------------------------------------------------------------------
	{
		Name:        "AMBIENT TEMPERATURE",
		Units:       []string{"celsius"},
		DefaultUnit: "celsius",
		Type:        "float64",
		Category:    "environment",
		Writable:    false,
		Indexed:     false,
		Description: "Ambient outside air temperature at the aircraft's current position.",
	},
	{
		Name:        "AMBIENT PRESSURE",
		Units:       []string{"inhg", "millibars"},
		DefaultUnit: "inhg",
		Type:        "float64",
		Category:    "environment",
		Writable:    false,
		Indexed:     false,
		Description: "Ambient atmospheric pressure at the aircraft's current position.",
	},
	{
		Name:        "AMBIENT WIND DIRECTION",
		Units:       []string{"degrees"},
		DefaultUnit: "degrees",
		Type:        "float64",
		Category:    "environment",
		Writable:    false,
		Indexed:     false,
		Description: "Direction from which the ambient wind is blowing (magnetic).",
	},
	{
		Name:        "AMBIENT WIND VELOCITY",
		Units:       []string{"knots", "meters per second"},
		DefaultUnit: "knots",
		Type:        "float64",
		Category:    "environment",
		Writable:    false,
		Indexed:     false,
		Description: "Speed of the ambient wind.",
	},
	{
		Name:        "AMBIENT VISIBILITY",
		Units:       []string{"meters", "kilometers"},
		DefaultUnit: "meters",
		Type:        "float64",
		Category:    "environment",
		Writable:    false,
		Indexed:     false,
		Description: "Current meteorological visibility.",
	},
	{
		Name:        "AMBIENT PRECIP RATE",
		Units:       []string{"millimeters of water"},
		DefaultUnit: "millimeters of water",
		Type:        "float64",
		Category:    "environment",
		Writable:    false,
		Indexed:     false,
		Description: "Current precipitation rate in millimeters of water per hour.",
	},
	{
		Name:        "AMBIENT PRECIP STATE",
		Units:       []string{"mask"},
		DefaultUnit: "mask",
		Type:        "float64",
		Category:    "environment",
		Writable:    false,
		Indexed:     false,
		Description: "Precipitation type bitmask (2=None, 4=Rain, 8=Snow).",
	},
	{
		Name:        "AMBIENT IN CLOUD",
		Units:       []string{"bool"},
		DefaultUnit: "bool",
		Type:        "bool",
		Category:    "environment",
		Writable:    false,
		Indexed:     false,
		Description: "Whether the aircraft is currently inside a cloud.",
	},
	{
		Name:        "AMBIENT IN SMOKE",
		Units:       []string{"bool"},
		DefaultUnit: "bool",
		Type:        "bool",
		Category:    "environment",
		Writable:    false,
		Indexed:     false,
		Description: "Whether the aircraft is currently inside a smoke volume.",
	},
	{
		Name:        "BAROMETER PRESSURE",
		Units:       []string{"millibars", "inhg"},
		DefaultUnit: "millibars",
		Type:        "float64",
		Category:    "environment",
		Writable:    false,
		Indexed:     false,
		Description: "Barometric pressure setting (QNH) in the altimeter.",
	},
	{
		Name:        "SEA LEVEL PRESSURE",
		Units:       []string{"millibars", "inhg"},
		DefaultUnit: "millibars",
		Type:        "float64",
		Category:    "environment",
		Writable:    false,
		Indexed:     false,
		Description: "Atmospheric pressure at mean sea level.",
	},
	{
		Name:        "DENSITY ALTITUDE",
		Units:       []string{"feet", "meters"},
		DefaultUnit: "feet",
		Type:        "float64",
		Category:    "environment",
		Writable:    false,
		Indexed:     false,
		Description: "Density altitude calculated from temperature and pressure.",
	},
	{
		Name:        "SEA LEVEL AMBIENT TEMPERATURE",
		Units:       []string{"celsius"},
		DefaultUnit: "celsius",
		Type:        "float64",
		Category:    "environment",
		Writable:    false,
		Indexed:     false,
		Description: "Ambient temperature at sea level.",
	},
	{
		Name:        "ENV SMOKE DENSITY",
		Units:       []string{"percent over 100"},
		DefaultUnit: "percent over 100",
		Type:        "float64",
		Category:    "environment",
		Writable:    false,
		Indexed:     false,
		Description: "Density of environmental smoke (0.0-1.0).",
	},
	{
		Name:        "ENV CLOUD DENSITY",
		Units:       []string{"percent over 100"},
		DefaultUnit: "percent over 100",
		Type:        "float64",
		Category:    "environment",
		Writable:    false,
		Indexed:     false,
		Description: "Density of cloud cover at the aircraft's position (0.0-1.0).",
	},
	{
		Name:        "GROUND ALTITUDE",
		Units:       []string{"feet", "meters"},
		DefaultUnit: "feet",
		Type:        "float64",
		Category:    "environment",
		Writable:    false,
		Indexed:     false,
		Description: "Altitude of the ground directly below the aircraft.",
	},

	// -------------------------------------------------------------------------
	// Simulator — time & date
	// -------------------------------------------------------------------------
	{
		Name:        "LOCAL TIME",
		Units:       []string{"seconds"},
		DefaultUnit: "seconds",
		Type:        "float64",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Local time expressed in seconds since midnight.",
	},
	{
		Name:        "ZULU TIME",
		Units:       []string{"seconds"},
		DefaultUnit: "seconds",
		Type:        "float64",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Zulu (UTC) time expressed in seconds since midnight.",
	},
	{
		Name:        "SIMULATION RATE",
		Units:       []string{"number"},
		DefaultUnit: "number",
		Type:        "float64",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Current simulation rate multiplier (1.0 = real time).",
	},
	{
		Name:        "SIMULATION TIME",
		Units:       []string{"seconds"},
		DefaultUnit: "seconds",
		Type:        "float64",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Total elapsed simulation time in seconds since session start.",
	},
	{
		Name:        "LOCAL DAY OF MONTH",
		Units:       []string{"number"},
		DefaultUnit: "number",
		Type:        "float64",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Current local day of the month (1-31).",
	},
	{
		Name:        "LOCAL MONTH OF YEAR",
		Units:       []string{"number"},
		DefaultUnit: "number",
		Type:        "float64",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Current local month of the year (1-12).",
	},
	{
		Name:        "LOCAL YEAR",
		Units:       []string{"number"},
		DefaultUnit: "number",
		Type:        "float64",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Current local year.",
	},
	{
		Name:        "ZULU DAY OF MONTH",
		Units:       []string{"number"},
		DefaultUnit: "number",
		Type:        "float64",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Current Zulu day of the month (1-31).",
	},
	{
		Name:        "ZULU MONTH OF YEAR",
		Units:       []string{"number"},
		DefaultUnit: "number",
		Type:        "float64",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Current Zulu month of the year (1-12).",
	},
	{
		Name:        "ZULU YEAR",
		Units:       []string{"number"},
		DefaultUnit: "number",
		Type:        "float64",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Current Zulu year.",
	},
	{
		Name:        "ZULU SUNRISE TIME",
		Units:       []string{"seconds"},
		DefaultUnit: "seconds",
		Type:        "float64",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Time of sunrise expressed as Zulu seconds since midnight.",
	},
	{
		Name:        "ZULU SUNSET TIME",
		Units:       []string{"seconds"},
		DefaultUnit: "seconds",
		Type:        "float64",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Time of sunset expressed as Zulu seconds since midnight.",
	},
	{
		Name:        "TIME ZONE OFFSET",
		Units:       []string{"seconds"},
		DefaultUnit: "seconds",
		Type:        "float64",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Current local time zone offset from UTC in seconds.",
	},

	// -------------------------------------------------------------------------
	// Simulator — units & settings
	// -------------------------------------------------------------------------
	{
		Name:        "TOOLTIP UNITS",
		Units:       []string{"number"},
		DefaultUnit: "number",
		Type:        "enum",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Unit system used for tooltip display (0=Imperial, 1=Metric).",
	},
	{
		Name:        "UNITS OF MEASURE",
		Units:       []string{"number"},
		DefaultUnit: "number",
		Type:        "enum",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Units of measure preference set by the user (0=Imperial, 1=Metric).",
	},

	// -------------------------------------------------------------------------
	// Simulator — ground & crash state
	// -------------------------------------------------------------------------
	{
		Name:        "SIM ON GROUND",
		Units:       []string{"bool"},
		DefaultUnit: "bool",
		Type:        "bool",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Whether the aircraft is on the ground.",
	},
	{
		Name:        "SURFACE TYPE",
		Units:       []string{"enum"},
		DefaultUnit: "enum",
		Type:        "enum",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Type of surface the aircraft is resting on.",
	},
	{
		Name:        "IS USER SIM",
		Units:       []string{"bool"},
		DefaultUnit: "bool",
		Type:        "bool",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Whether the object is the user's aircraft.",
	},
	{
		Name:        "TOTAL WEIGHT",
		Units:       []string{"pounds", "kilograms"},
		DefaultUnit: "pounds",
		Type:        "float64",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Total weight of the aircraft including fuel and payload.",
	},
	{
		Name:        "CRASH FLAG",
		Units:       []string{"enum"},
		DefaultUnit: "enum",
		Type:        "enum",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Crash detection flag bitmask.",
	},

	// -------------------------------------------------------------------------
	// Simulator — camera & view
	// -------------------------------------------------------------------------
	{
		Name:        "CAMERA STATE",
		Units:       []string{"enum"},
		DefaultUnit: "enum",
		Type:        "enum",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Current camera state (cockpit, external, drone, etc.).",
	},
	{
		Name:        "CAMERA SUBSTATE",
		Units:       []string{"enum"},
		DefaultUnit: "enum",
		Type:        "enum",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Sub-state of the current camera state.",
	},
	{
		Name:        "CAMERA VIEW TYPE INDEX",
		Units:       []string{"number"},
		DefaultUnit: "number",
		Type:        "float64",
		Category:    "simulator",
		Writable:    false,
		Indexed:     true,
		Description: "Camera view type index for the indexed camera.",
	},
	{
		Name:        "SMART CAMERA ACTIVE",
		Units:       []string{"bool"},
		DefaultUnit: "bool",
		Type:        "bool",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Whether the smart camera feature is active.",
	},

	// -------------------------------------------------------------------------
	// Simulator — realism & accessibility
	// -------------------------------------------------------------------------
	{
		Name:        "REALISM",
		Units:       []string{"number"},
		DefaultUnit: "number",
		Type:        "float64",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Current realism setting value.",
	},
	{
		Name:        "VISUAL MODEL RADIUS",
		Units:       []string{"meters", "feet"},
		DefaultUnit: "meters",
		Type:        "float64",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Radius of the visual model bounding sphere.",
	},
	{
		Name:        "SIM DISABLED",
		Units:       []string{"bool"},
		DefaultUnit: "bool",
		Type:        "bool",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Whether the simulator is disabled (paused via a disable call).",
	},
	{
		Name:        "REALISM CRASH DETECTION",
		Units:       []string{"bool"},
		DefaultUnit: "bool",
		Type:        "bool",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Whether crash detection is enabled in the realism settings.",
	},
	{
		Name:        "REALISM CRASH WITH OTHERS",
		Units:       []string{"bool"},
		DefaultUnit: "bool",
		Type:        "bool",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Whether collision with other aircraft is enabled in realism settings.",
	},
	{
		Name:        "TRACK IR ENABLE",
		Units:       []string{"bool"},
		DefaultUnit: "bool",
		Type:        "bool",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Whether TrackIR head tracking is enabled.",
	},
	{
		Name:        "USER INPUT ENABLED",
		Units:       []string{"bool"},
		DefaultUnit: "bool",
		Type:        "bool",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Whether user input (keyboard, joystick) is currently enabled.",
	},
	{
		Name:        "MAGVAR",
		Units:       []string{"degrees", "radians"},
		DefaultUnit: "degrees",
		Type:        "float64",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Magnetic variation at the current position.",
	},
	{
		Name:        "HAND ANIM STATE",
		Units:       []string{"number"},
		DefaultUnit: "number",
		Type:        "enum",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "State of the hand animation (VR controller interaction).",
	},
	{
		Name:        "HIDE AVATAR IN AIRCRAFT",
		Units:       []string{"bool"},
		DefaultUnit: "bool",
		Type:        "bool",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Whether the avatar/pilot model is hidden inside the cockpit.",
	},
	{
		Name:        "MISSION SCORE",
		Units:       []string{"number"},
		DefaultUnit: "number",
		Type:        "float64",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Current mission score.",
	},
	{
		Name:        "PARACHUTE OPEN",
		Units:       []string{"bool"},
		DefaultUnit: "bool",
		Type:        "bool",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Whether the parachute is open.",
	},

	// -------------------------------------------------------------------------
	// Simulator — VR & controller state
	// -------------------------------------------------------------------------
	{
		Name:        "IS IN VR",
		Units:       []string{"bool"},
		DefaultUnit: "bool",
		Type:        "bool",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Whether the simulator is running in VR mode.",
	},
	{
		Name:        "IS USING MOTION CONTROLLERS",
		Units:       []string{"bool"},
		DefaultUnit: "bool",
		Type:        "bool",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Whether VR motion controllers are in use.",
	},
	{
		Name:        "IS USING JOYSTICK THROTTLE",
		Units:       []string{"bool"},
		DefaultUnit: "bool",
		Type:        "bool",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Whether a physical joystick throttle axis is in use.",
	},
	{
		Name:        "IS IN RTC",
		Units:       []string{"bool"},
		DefaultUnit: "bool",
		Type:        "bool",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Whether the user is connected to a real-time collaboration session.",
	},
	{
		Name:        "IS AVATAR",
		Units:       []string{"bool"},
		DefaultUnit: "bool",
		Type:        "bool",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Whether the object is an avatar (pedestrian, ground worker, etc.).",
	},
	{
		Name:        "IS AIRCRAFT",
		Units:       []string{"bool"},
		DefaultUnit: "bool",
		Type:        "bool",
		Category:    "simulator",
		Writable:    false,
		Indexed:     false,
		Description: "Whether the object is classified as an aircraft.",
	},

	// -------------------------------------------------------------------------
	// Autopilot — mode engagement flags & hold targets
	// -------------------------------------------------------------------------
	{
		Name:        "AUTOPILOT HEADING LOCK",
		Units:       []string{"bool"},
		DefaultUnit: "bool",
		Type:        "bool",
		Category:    "autopilot",
		Writable:    true,
		Indexed:     false,
		Description: "Autopilot heading lock mode engagement state (true = engaged).",
	},
	{
		Name:        "AUTOPILOT ALTITUDE LOCK",
		Units:       []string{"bool"},
		DefaultUnit: "bool",
		Type:        "bool",
		Category:    "autopilot",
		Writable:    true,
		Indexed:     false,
		Description: "Autopilot altitude lock mode engagement state (true = engaged).",
	},
	{
		Name:        "AUTOPILOT VERTICAL HOLD",
		Units:       []string{"bool"},
		DefaultUnit: "bool",
		Type:        "bool",
		Category:    "autopilot",
		Writable:    true,
		Indexed:     false,
		Description: "Autopilot vertical speed hold mode engagement state (true = engaged).",
	},
	{
		Name:        "AUTOPILOT VERTICAL HOLD VAR",
		Units:       []string{"feet per minute", "meters per second"},
		DefaultUnit: "feet per minute",
		Type:        "float64",
		Category:    "autopilot",
		Writable:    true,
		Indexed:     false,
		Description: "Target vertical speed for the autopilot vertical hold mode in feet per minute.",
	},
	{
		Name:        "AUTOPILOT AIRSPEED HOLD",
		Units:       []string{"bool"},
		DefaultUnit: "bool",
		Type:        "bool",
		Category:    "autopilot",
		Writable:    true,
		Indexed:     false,
		Description: "Autopilot airspeed hold mode engagement state (true = engaged).",
	},
	{
		Name:        "AUTOPILOT AIRSPEED HOLD VAR",
		Units:       []string{"knots", "meters per second"},
		DefaultUnit: "knots",
		Type:        "float64",
		Category:    "autopilot",
		Writable:    true,
		Indexed:     false,
		Description: "Target airspeed for the autopilot airspeed hold mode in knots.",
	},
	{
		Name:        "AUTOPILOT NAV1 LOCK",
		Units:       []string{"bool"},
		DefaultUnit: "bool",
		Type:        "bool",
		Category:    "autopilot",
		Writable:    true,
		Indexed:     false,
		Description: "Autopilot NAV1 lock mode engagement state (true = engaged).",
	},
	{
		Name:        "AUTOPILOT APPROACH HOLD",
		Units:       []string{"bool"},
		DefaultUnit: "bool",
		Type:        "bool",
		Category:    "autopilot",
		Writable:    true,
		Indexed:     false,
		Description: "Autopilot approach hold mode engagement state (true = engaged).",
	},

	// -------------------------------------------------------------------------
	// Navigation — COM / NAV / ADF radios
	// -------------------------------------------------------------------------
	{
		Name:        "COM STANDBY FREQUENCY",
		Units:       []string{"mhz"},
		DefaultUnit: "mhz",
		Type:        "float64",
		Category:    "navigation",
		Writable:    true,
		Indexed:     true,
		Description: "Standby COM radio frequency in MHz for the indexed radio (e.g., COM STANDBY FREQUENCY:1).",
	},
	{
		Name:        "NAV ACTIVE FREQUENCY",
		Units:       []string{"mhz"},
		DefaultUnit: "mhz",
		Type:        "float64",
		Category:    "navigation",
		Writable:    false,
		Indexed:     true,
		Description: "Active NAV radio frequency in MHz for the indexed radio (e.g., NAV ACTIVE FREQUENCY:1).",
	},
	{
		Name:        "NAV STANDBY FREQUENCY",
		Units:       []string{"mhz"},
		DefaultUnit: "mhz",
		Type:        "float64",
		Category:    "navigation",
		Writable:    true,
		Indexed:     true,
		Description: "Standby NAV radio frequency in MHz for the indexed radio (e.g., NAV STANDBY FREQUENCY:1).",
	},
	{
		Name:        "ADF ACTIVE FREQUENCY",
		Units:       []string{"hz"},
		DefaultUnit: "hz",
		Type:        "float64",
		Category:    "navigation",
		Writable:    false,
		Indexed:     true,
		Description: "Active ADF receiver frequency in Hz for the indexed ADF (e.g., ADF ACTIVE FREQUENCY:1).",
	},
	{
		Name:        "ADF RADIAL",
		Units:       []string{"degrees"},
		DefaultUnit: "degrees",
		Type:        "float64",
		Category:    "navigation",
		Writable:    false,
		Indexed:     true,
		Description: "Radial bearing from the ADF station in degrees for the indexed ADF (e.g., ADF RADIAL:1).",
	},

	// -------------------------------------------------------------------------
	// Navigation — GPS
	// -------------------------------------------------------------------------
	{
		Name:        "GPS GROUND SPEED",
		Units:       []string{"meters per second", "knots"},
		DefaultUnit: "meters per second",
		Type:        "float64",
		Category:    "navigation",
		Writable:    false,
		Indexed:     false,
		Description: "GPS-derived ground speed in meters per second.",
	},
	{
		Name:        "GPS GROUND MAGNETIC TRACK",
		Units:       []string{"degrees", "radians"},
		DefaultUnit: "degrees",
		Type:        "float64",
		Category:    "navigation",
		Writable:    false,
		Indexed:     false,
		Description: "GPS-derived ground track angle relative to magnetic north in degrees.",
	},
	{
		Name:        "GPS POSITION LAT",
		Units:       []string{"degrees", "radians"},
		DefaultUnit: "degrees",
		Type:        "float64",
		Category:    "navigation",
		Writable:    false,
		Indexed:     false,
		Description: "GPS latitude position in degrees north of the equator.",
	},
	{
		Name:        "GPS POSITION LON",
		Units:       []string{"degrees", "radians"},
		DefaultUnit: "degrees",
		Type:        "float64",
		Category:    "navigation",
		Writable:    false,
		Indexed:     false,
		Description: "GPS longitude position in degrees east of the prime meridian.",
	},
}
