package types

import "testing"

// TestFlagValues pins flag constants to the SimConnect.h values. Flags are
// bit masks; defining them with iota silently produced wrong values for the
// event flags (#310).
func TestFlagValues(t *testing.T) {
	for _, c := range []struct {
		name      string
		got, want uint32
	}{
		{"SIMCONNECT_EVENT_FLAG_DEFAULT", uint32(SIMCONNECT_EVENT_FLAG_DEFAULT), 0x00},
		{"SIMCONNECT_EVENT_FLAG_FAST_REPEAT_TIMER", uint32(SIMCONNECT_EVENT_FLAG_FAST_REPEAT_TIMER), 0x01},
		{"SIMCONNECT_EVENT_FLAG_SLOW_REPEAT_TIMER", uint32(SIMCONNECT_EVENT_FLAG_SLOW_REPEAT_TIMER), 0x02},
		{"SIMCONNECT_EVENT_FLAG_GROUPID_IS_PRIORITY", uint32(SIMCONNECT_EVENT_FLAG_GROUPID_IS_PRIORITY), 0x10},
		{"SIMCONNECT_DATA_REQUEST_FLAG_DEFAULT", uint32(SIMCONNECT_DATA_REQUEST_FLAG_DEFAULT), 0x00},
		{"SIMCONNECT_DATA_REQUEST_FLAG_CHANGED", uint32(SIMCONNECT_DATA_REQUEST_FLAG_CHANGED), 0x01},
		{"SIMCONNECT_DATA_REQUEST_FLAG_TAGGED", uint32(SIMCONNECT_DATA_REQUEST_FLAG_TAGGED), 0x02},
		{"SIMCONNECT_CLIENT_DATA_REQUEST_FLAG_CHANGED", uint32(SIMCONNECT_CLIENT_DATA_REQUEST_FLAG_CHANGED), 0x01},
		{"SIMCONNECT_CLIENT_DATA_REQUEST_FLAG_TAGGED", uint32(SIMCONNECT_CLIENT_DATA_REQUEST_FLAG_TAGGED), 0x02},
		{"SIMCONNECT_DATA_SET_FLAG_TAGGED", uint32(SIMCONNECT_DATA_SET_FLAG_TAGGED), 0x01},
		{"SIMCONNECT_CREATE_CLIENT_DATA_FLAG_READ_ONLY", uint32(SIMCONNECT_CREATE_CLIENT_DATA_FLAG_READ_ONLY), 0x01},
	} {
		if c.got != c.want {
			t.Errorf("%s = %#x, want %#x", c.name, c.got, c.want)
		}
	}
}
