//go:build windows
// +build windows

package types

// https://docs.flightsimulator.com/msfs2024/html/6_Programming_APIs/SimConnect/API_Reference/Structures_And_Enumerations/SIMCONNECT_PERIOD.htm
type SIMCONNECT_PERIOD DWORD

const (
	SIMCONNECT_PERIOD_NEVER SIMCONNECT_PERIOD = iota
	SIMCONNECT_PERIOD_ONCE
	SIMCONNECT_PERIOD_VISUAL_FRAME
	SIMCONNECT_PERIOD_SIM_FRAME
	SIMCONNECT_PERIOD_SECOND
)

// https://docs.flightsimulator.com/msfs2024/html/6_Programming_APIs/SimConnect/API_Reference/Structures_And_Enumerations/SIMCONNECT_CLIENT_DATA_PERIOD.htm
type SIMCONNECT_CLIENT_DATA_PERIOD DWORD

const (
	SIMCONNECT_CLIENT_DATA_PERIOD_NEVER SIMCONNECT_CLIENT_DATA_PERIOD = iota
	SIMCONNECT_CLIENT_DATA_PERIOD_ONCE
	SIMCONNECT_CLIENT_DATA_PERIOD_VISUAL_FRAME
	SIMCONNECT_CLIENT_DATA_PERIOD_ON_SET
	SIMCONNECT_CLIENT_DATA_PERIOD_SECOND
)
