//go:build windows
// +build windows

package types

type SIMCONNECT_SIMOBJECT_TYPE DWORD

const (
	SIMCONNECT_SIMOBJECT_TYPE_USER SIMCONNECT_SIMOBJECT_TYPE = iota
	SIMCONNECT_SIMOBJECT_TYPE_ALL
	SIMCONNECT_SIMOBJECT_TYPE_AIRCRAFT
	SIMCONNECT_SIMOBJECT_TYPE_HELICOPTER
	SIMCONNECT_SIMOBJECT_TYPE_BOAT
	SIMCONNECT_SIMOBJECT_TYPE_GROUND
)
